cart={
    "producto":"libro",
    "cantidad":3,
    "precio": 2.99
    }

persona={
    "Nombres":"Ryan",
    "Apellidos":"Ray"
}

print(dir(persona))

print(persona.keys())

#obtener los datos
print(persona.items())

#eliminar diccionario
#del persona

#limpiar el diccionario
#persona.clear()

#creando una lista q tenga varios diccionarios
productos=[
    {"nombre": "libro","precio":10.33},
    {"nombre": "laptop","precio": 512}
]
print(productos)

