#Blucles
alimentos=["manzanas","peras","arroz","azucar","cereales"]

#bucle q recorre los elementos de la lista y los imprime
for alimento in alimentos:
    if alimento=="azucar":
        print("Tienes q comprar esto")
        print(alimento)

for numero in range(1,8)        :
    print(numero)

for letra in "hello"        :
    print(letra)


contador=4
while contador<=10:
    print(contador)
    contador=contador+1
    